apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        version: v2.0.0
    spec:
      containers:
      - name: my-app
        image: beekoan/udacity_course4
        command: [
          "/bin/bash", 
          "-c", 
          "python3 app.py"
          ]
        
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: capstonebeeko
spec:
  type: LoadBalancer
  selector:
    app: capstonebeeko
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 80
